### PR TITLE
build(android): fix build breaks with flutter v3.29.0

### LINKED ISSUE #411: Errors while compiling on android with Flutter 3.29.0
Plugin worked correctly until I updated flutter version. Once I updated flutter to 3.29.0 it is throwing following errors while building apk:

`
/Users/macmini/.pub-cache/hosted/pub.dev/wifi_iot-0.3.19+1/android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java:43: error: cannot find symbol
import io.flutter.plugin.common.PluginRegistry.Registrar;
                                              ^
  symbol:   class Registrar
  location: interface PluginRegistry
/Users/macmini/.pub-cache/hosted/pub.dev/wifi_iot-0.3.19+1/android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java:45: error: cannot find symbol
import io.flutter.plugin.common.PluginRegistry.ViewDestroyListener;
                                              ^
  symbol:   class ViewDestroyListener
  location: interface PluginRegistry
/Users/macmini/.pub-cache/hosted/pub.dev/wifi_iot-0.3.19+1/android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java:46: error: cannot find symbol
import io.flutter.view.FlutterNativeView;
                      ^
  symbol:   class FlutterNativeView
  location: package io.flutter.view
/Users/macmini/.pub-cache/hosted/pub.dev/wifi_iot-0.3.19+1/android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java:125: error: cannot find symbol
  public static void registerWith(Registrar registrar) {
                                  ^
  symbol:   class Registrar
  location: class WifiIotPlugin
/Users/macmini/.pub-cache/hosted/pub.dev/wifi_iot-0.3.19+1/android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java:136: error: cannot find symbol
        new ViewDestroyListener() {
            ^
  symbol:   class ViewDestroyListener
  location: class WifiIotPlugin
/Users/macmini/.pub-cache/hosted/pub.dev/wifi_iot-0.3.19+1/android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java:138: error: cannot find symbol
          public boolean onViewDestroy(FlutterNativeView view) {
                                       ^
  symbol: class FlutterNativeView
/Users/macmini/.pub-cache/hosted/pub.dev/wifi_iot-0.3.19+1/android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java:137: error: method does not override or implement a method from a supertype
          @Override
          ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
7 errors
3 warnings

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':wifi_iot:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.`

### PR DESCRIPTION
**Pull request by bazookon**
Fix Android Embedding V2, works with flutter 3.29

Closes #411

### CODE REVIEW

**Comment by daadu** [comment]
@bazookon Can you sync the master of this repo, I have fixed the CI issues.

Also remove unnecessary commited files  -- fvm related, cxx related -- feel free to add ignore rules for them as well.

**Comment by daadu** [comment]
Also make similar changes for `wifi_scan` package as well.

If you can give me access to your fork, will fix this things myself -- if you are busy.

**Comment by daadu** [comment]
@bazookon I can push now! Not sure if you did any changes!

**Comment by daadu** [comment]
Implementing changes based on --> https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply

**Comment by daadu** [comment]
This has landed in pub.dev

@bazookon Thanks for your contribution, check yourself in the [CONTRIBUTORS.md](https://github.com/flutternetwork/WiFiFlutter/blob/master/CONTRIBUTORS.md) file!
